services:
  tgbot:
    container_name: tgbot
    image: ghcr.io/openai-all-stars/tgbot:latest
    volumes:
      - ~/data:/app/data
    environment:
      - HOST_INTERNAL=host.docker.internal
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - TG_TOKEN=$TG_TOKEN
      - SECRET_INVITE=$SECRET_INVITE
      - YANDEX_FOLDERID=$YANDEX_FOLDERID
      - YANDEX_SEARCH_API_KEY=$YANDEX_SEARCH_API_KEY
      - SENTRY_DSN=$SENTRY_DSN
      - SQLITE_PATH=/app/data/db.sqlite3
