name: deploy

on:
  pull_request:
    types:
      - closed
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: install ssh keys
          # check this thread to understand why its needed:
          # <https://stackoverflow.com/a/70447517>
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        - name: load secrets
          uses: oNaiPs/secrets-to-env-action@v1.5
          with:
            secrets: ${{ toJSON(secrets) }}
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.x
        - name: Install Ansible
          run: |
            python -m pip install --upgrade pip
            pip install ansible
        - name: Run Ansible Playbook
          run: ansible-playbook playbook.yml
