name: tests

on:
  pull_request:
    branches: [ "main" ]

jobs:

    tests:
        name: Tests
        runs-on: ubuntu-latest

        steps:
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.12
        - uses: actions/checkout@v4
        - name: Install tox
          run: pip install tox
        - name: Run tests
          run: tox
